// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/guru": {
    params: {};
  };
  "/guru/scan": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/login" | "/admin" | "/guru" | "/guru/scan";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "admin/layout.tsx": {
    id: "admin/layout";
    page: "/admin";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin";
  };
  "guru/layout.tsx": {
    id: "guru/layout";
    page: "/guru" | "/guru/scan";
  };
  "routes/guru/home.tsx": {
    id: "routes/guru/home";
    page: "/guru";
  };
  "routes/guru/scan.tsx": {
    id: "routes/guru/scan";
    page: "/guru/scan";
  };
};