/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginSiswaRouteImport } from './routes/login-siswa'
import { Route as LoginGuruRouteImport } from './routes/login-guru'
import { Route as AboutRouteImport } from './routes/about'
import { Route as Auth_siswaRouteImport } from './routes/_auth_siswa'
import { Route as Auth_guruRouteImport } from './routes/_auth_guru'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Auth_siswaSiswaRouteImport } from './routes/_auth_siswa/siswa'
import { Route as Auth_guruGuruRouteImport } from './routes/_auth_guru/guru'
import { Route as Auth_guruAdminRouteImport } from './routes/_auth_guru/admin'
import { Route as Auth_siswaSiswaIndexRouteImport } from './routes/_auth_siswa/siswa/index'
import { Route as Auth_guruGuruIndexRouteImport } from './routes/_auth_guru/guru/index'
import { Route as Auth_guruAdminIndexRouteImport } from './routes/_auth_guru/admin/index'
import { Route as Auth_siswaSiswaGenerateRouteImport } from './routes/_auth_siswa/siswa/generate'
import { Route as Auth_siswaSiswaMapelidRouteImport } from './routes/_auth_siswa/siswa/$mapelid'
import { Route as Auth_guruGuruScanRouteImport } from './routes/_auth_guru/guru/scan'
import { Route as Auth_guruGuruJadwalRouteImport } from './routes/_auth_guru/guru/jadwal'
import { Route as Auth_guruAdminRuanganRouteImport } from './routes/_auth_guru/admin/ruangan'
import { Route as Auth_guruAdminMapelRouteImport } from './routes/_auth_guru/admin/mapel'
import { Route as Auth_guruAdminKetuaKelasRouteImport } from './routes/_auth_guru/admin/ketua-kelas'
import { Route as Auth_guruAdminKelasRouteImport } from './routes/_auth_guru/admin/kelas'
import { Route as Auth_guruAdminJadwalajarRouteImport } from './routes/_auth_guru/admin/jadwalajar'
import { Route as Auth_guruAdminGuruRouteImport } from './routes/_auth_guru/admin/guru'

const LoginSiswaRoute = LoginSiswaRouteImport.update({
  id: '/login-siswa',
  path: '/login-siswa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginGuruRoute = LoginGuruRouteImport.update({
  id: '/login-guru',
  path: '/login-guru',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth_siswaRoute = Auth_siswaRouteImport.update({
  id: '/_auth_siswa',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth_guruRoute = Auth_guruRouteImport.update({
  id: '/_auth_guru',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Auth_siswaSiswaRoute = Auth_siswaSiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => Auth_siswaRoute,
} as any)
const Auth_guruGuruRoute = Auth_guruGuruRouteImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => Auth_guruRoute,
} as any)
const Auth_guruAdminRoute = Auth_guruAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => Auth_guruRoute,
} as any)
const Auth_siswaSiswaIndexRoute = Auth_siswaSiswaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Auth_siswaSiswaRoute,
} as any)
const Auth_guruGuruIndexRoute = Auth_guruGuruIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Auth_guruGuruRoute,
} as any)
const Auth_guruAdminIndexRoute = Auth_guruAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Auth_guruAdminRoute,
} as any)
const Auth_siswaSiswaGenerateRoute = Auth_siswaSiswaGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => Auth_siswaSiswaRoute,
} as any)
const Auth_siswaSiswaMapelidRoute = Auth_siswaSiswaMapelidRouteImport.update({
  id: '/$mapelid',
  path: '/$mapelid',
  getParentRoute: () => Auth_siswaSiswaRoute,
} as any)
const Auth_guruGuruScanRoute = Auth_guruGuruScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => Auth_guruGuruRoute,
} as any)
const Auth_guruGuruJadwalRoute = Auth_guruGuruJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => Auth_guruGuruRoute,
} as any)
const Auth_guruAdminRuanganRoute = Auth_guruAdminRuanganRouteImport.update({
  id: '/ruangan',
  path: '/ruangan',
  getParentRoute: () => Auth_guruAdminRoute,
} as any)
const Auth_guruAdminMapelRoute = Auth_guruAdminMapelRouteImport.update({
  id: '/mapel',
  path: '/mapel',
  getParentRoute: () => Auth_guruAdminRoute,
} as any)
const Auth_guruAdminKetuaKelasRoute =
  Auth_guruAdminKetuaKelasRouteImport.update({
    id: '/ketua-kelas',
    path: '/ketua-kelas',
    getParentRoute: () => Auth_guruAdminRoute,
  } as any)
const Auth_guruAdminKelasRoute = Auth_guruAdminKelasRouteImport.update({
  id: '/kelas',
  path: '/kelas',
  getParentRoute: () => Auth_guruAdminRoute,
} as any)
const Auth_guruAdminJadwalajarRoute =
  Auth_guruAdminJadwalajarRouteImport.update({
    id: '/jadwalajar',
    path: '/jadwalajar',
    getParentRoute: () => Auth_guruAdminRoute,
  } as any)
const Auth_guruAdminGuruRoute = Auth_guruAdminGuruRouteImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => Auth_guruAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof Auth_siswaRouteWithChildren
  '/about': typeof AboutRoute
  '/login-guru': typeof LoginGuruRoute
  '/login-siswa': typeof LoginSiswaRoute
  '/admin': typeof Auth_guruAdminRouteWithChildren
  '/guru': typeof Auth_guruGuruRouteWithChildren
  '/siswa': typeof Auth_siswaSiswaRouteWithChildren
  '/admin/guru': typeof Auth_guruAdminGuruRoute
  '/admin/jadwalajar': typeof Auth_guruAdminJadwalajarRoute
  '/admin/kelas': typeof Auth_guruAdminKelasRoute
  '/admin/ketua-kelas': typeof Auth_guruAdminKetuaKelasRoute
  '/admin/mapel': typeof Auth_guruAdminMapelRoute
  '/admin/ruangan': typeof Auth_guruAdminRuanganRoute
  '/guru/jadwal': typeof Auth_guruGuruJadwalRoute
  '/guru/scan': typeof Auth_guruGuruScanRoute
  '/siswa/$mapelid': typeof Auth_siswaSiswaMapelidRoute
  '/siswa/generate': typeof Auth_siswaSiswaGenerateRoute
  '/admin/': typeof Auth_guruAdminIndexRoute
  '/guru/': typeof Auth_guruGuruIndexRoute
  '/siswa/': typeof Auth_siswaSiswaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof Auth_siswaRouteWithChildren
  '/about': typeof AboutRoute
  '/login-guru': typeof LoginGuruRoute
  '/login-siswa': typeof LoginSiswaRoute
  '/admin/guru': typeof Auth_guruAdminGuruRoute
  '/admin/jadwalajar': typeof Auth_guruAdminJadwalajarRoute
  '/admin/kelas': typeof Auth_guruAdminKelasRoute
  '/admin/ketua-kelas': typeof Auth_guruAdminKetuaKelasRoute
  '/admin/mapel': typeof Auth_guruAdminMapelRoute
  '/admin/ruangan': typeof Auth_guruAdminRuanganRoute
  '/guru/jadwal': typeof Auth_guruGuruJadwalRoute
  '/guru/scan': typeof Auth_guruGuruScanRoute
  '/siswa/$mapelid': typeof Auth_siswaSiswaMapelidRoute
  '/siswa/generate': typeof Auth_siswaSiswaGenerateRoute
  '/admin': typeof Auth_guruAdminIndexRoute
  '/guru': typeof Auth_guruGuruIndexRoute
  '/siswa': typeof Auth_siswaSiswaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth_guru': typeof Auth_guruRouteWithChildren
  '/_auth_siswa': typeof Auth_siswaRouteWithChildren
  '/about': typeof AboutRoute
  '/login-guru': typeof LoginGuruRoute
  '/login-siswa': typeof LoginSiswaRoute
  '/_auth_guru/admin': typeof Auth_guruAdminRouteWithChildren
  '/_auth_guru/guru': typeof Auth_guruGuruRouteWithChildren
  '/_auth_siswa/siswa': typeof Auth_siswaSiswaRouteWithChildren
  '/_auth_guru/admin/guru': typeof Auth_guruAdminGuruRoute
  '/_auth_guru/admin/jadwalajar': typeof Auth_guruAdminJadwalajarRoute
  '/_auth_guru/admin/kelas': typeof Auth_guruAdminKelasRoute
  '/_auth_guru/admin/ketua-kelas': typeof Auth_guruAdminKetuaKelasRoute
  '/_auth_guru/admin/mapel': typeof Auth_guruAdminMapelRoute
  '/_auth_guru/admin/ruangan': typeof Auth_guruAdminRuanganRoute
  '/_auth_guru/guru/jadwal': typeof Auth_guruGuruJadwalRoute
  '/_auth_guru/guru/scan': typeof Auth_guruGuruScanRoute
  '/_auth_siswa/siswa/$mapelid': typeof Auth_siswaSiswaMapelidRoute
  '/_auth_siswa/siswa/generate': typeof Auth_siswaSiswaGenerateRoute
  '/_auth_guru/admin/': typeof Auth_guruAdminIndexRoute
  '/_auth_guru/guru/': typeof Auth_guruGuruIndexRoute
  '/_auth_siswa/siswa/': typeof Auth_siswaSiswaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/login-guru'
    | '/login-siswa'
    | '/admin'
    | '/guru'
    | '/siswa'
    | '/admin/guru'
    | '/admin/jadwalajar'
    | '/admin/kelas'
    | '/admin/ketua-kelas'
    | '/admin/mapel'
    | '/admin/ruangan'
    | '/guru/jadwal'
    | '/guru/scan'
    | '/siswa/$mapelid'
    | '/siswa/generate'
    | '/admin/'
    | '/guru/'
    | '/siswa/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/login-guru'
    | '/login-siswa'
    | '/admin/guru'
    | '/admin/jadwalajar'
    | '/admin/kelas'
    | '/admin/ketua-kelas'
    | '/admin/mapel'
    | '/admin/ruangan'
    | '/guru/jadwal'
    | '/guru/scan'
    | '/siswa/$mapelid'
    | '/siswa/generate'
    | '/admin'
    | '/guru'
    | '/siswa'
  id:
    | '__root__'
    | '/'
    | '/_auth_guru'
    | '/_auth_siswa'
    | '/about'
    | '/login-guru'
    | '/login-siswa'
    | '/_auth_guru/admin'
    | '/_auth_guru/guru'
    | '/_auth_siswa/siswa'
    | '/_auth_guru/admin/guru'
    | '/_auth_guru/admin/jadwalajar'
    | '/_auth_guru/admin/kelas'
    | '/_auth_guru/admin/ketua-kelas'
    | '/_auth_guru/admin/mapel'
    | '/_auth_guru/admin/ruangan'
    | '/_auth_guru/guru/jadwal'
    | '/_auth_guru/guru/scan'
    | '/_auth_siswa/siswa/$mapelid'
    | '/_auth_siswa/siswa/generate'
    | '/_auth_guru/admin/'
    | '/_auth_guru/guru/'
    | '/_auth_siswa/siswa/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Auth_guruRoute: typeof Auth_guruRouteWithChildren
  Auth_siswaRoute: typeof Auth_siswaRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginGuruRoute: typeof LoginGuruRoute
  LoginSiswaRoute: typeof LoginSiswaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-siswa': {
      id: '/login-siswa'
      path: '/login-siswa'
      fullPath: '/login-siswa'
      preLoaderRoute: typeof LoginSiswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-guru': {
      id: '/login-guru'
      path: '/login-guru'
      fullPath: '/login-guru'
      preLoaderRoute: typeof LoginGuruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth_siswa': {
      id: '/_auth_siswa'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Auth_siswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth_guru': {
      id: '/_auth_guru'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Auth_guruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth_siswa/siswa': {
      id: '/_auth_siswa/siswa'
      path: '/siswa'
      fullPath: '/siswa'
      preLoaderRoute: typeof Auth_siswaSiswaRouteImport
      parentRoute: typeof Auth_siswaRoute
    }
    '/_auth_guru/guru': {
      id: '/_auth_guru/guru'
      path: '/guru'
      fullPath: '/guru'
      preLoaderRoute: typeof Auth_guruGuruRouteImport
      parentRoute: typeof Auth_guruRoute
    }
    '/_auth_guru/admin': {
      id: '/_auth_guru/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Auth_guruAdminRouteImport
      parentRoute: typeof Auth_guruRoute
    }
    '/_auth_siswa/siswa/': {
      id: '/_auth_siswa/siswa/'
      path: '/'
      fullPath: '/siswa/'
      preLoaderRoute: typeof Auth_siswaSiswaIndexRouteImport
      parentRoute: typeof Auth_siswaSiswaRoute
    }
    '/_auth_guru/guru/': {
      id: '/_auth_guru/guru/'
      path: '/'
      fullPath: '/guru/'
      preLoaderRoute: typeof Auth_guruGuruIndexRouteImport
      parentRoute: typeof Auth_guruGuruRoute
    }
    '/_auth_guru/admin/': {
      id: '/_auth_guru/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof Auth_guruAdminIndexRouteImport
      parentRoute: typeof Auth_guruAdminRoute
    }
    '/_auth_siswa/siswa/generate': {
      id: '/_auth_siswa/siswa/generate'
      path: '/generate'
      fullPath: '/siswa/generate'
      preLoaderRoute: typeof Auth_siswaSiswaGenerateRouteImport
      parentRoute: typeof Auth_siswaSiswaRoute
    }
    '/_auth_siswa/siswa/$mapelid': {
      id: '/_auth_siswa/siswa/$mapelid'
      path: '/$mapelid'
      fullPath: '/siswa/$mapelid'
      preLoaderRoute: typeof Auth_siswaSiswaMapelidRouteImport
      parentRoute: typeof Auth_siswaSiswaRoute
    }
    '/_auth_guru/guru/scan': {
      id: '/_auth_guru/guru/scan'
      path: '/scan'
      fullPath: '/guru/scan'
      preLoaderRoute: typeof Auth_guruGuruScanRouteImport
      parentRoute: typeof Auth_guruGuruRoute
    }
    '/_auth_guru/guru/jadwal': {
      id: '/_auth_guru/guru/jadwal'
      path: '/jadwal'
      fullPath: '/guru/jadwal'
      preLoaderRoute: typeof Auth_guruGuruJadwalRouteImport
      parentRoute: typeof Auth_guruGuruRoute
    }
    '/_auth_guru/admin/ruangan': {
      id: '/_auth_guru/admin/ruangan'
      path: '/ruangan'
      fullPath: '/admin/ruangan'
      preLoaderRoute: typeof Auth_guruAdminRuanganRouteImport
      parentRoute: typeof Auth_guruAdminRoute
    }
    '/_auth_guru/admin/mapel': {
      id: '/_auth_guru/admin/mapel'
      path: '/mapel'
      fullPath: '/admin/mapel'
      preLoaderRoute: typeof Auth_guruAdminMapelRouteImport
      parentRoute: typeof Auth_guruAdminRoute
    }
    '/_auth_guru/admin/ketua-kelas': {
      id: '/_auth_guru/admin/ketua-kelas'
      path: '/ketua-kelas'
      fullPath: '/admin/ketua-kelas'
      preLoaderRoute: typeof Auth_guruAdminKetuaKelasRouteImport
      parentRoute: typeof Auth_guruAdminRoute
    }
    '/_auth_guru/admin/kelas': {
      id: '/_auth_guru/admin/kelas'
      path: '/kelas'
      fullPath: '/admin/kelas'
      preLoaderRoute: typeof Auth_guruAdminKelasRouteImport
      parentRoute: typeof Auth_guruAdminRoute
    }
    '/_auth_guru/admin/jadwalajar': {
      id: '/_auth_guru/admin/jadwalajar'
      path: '/jadwalajar'
      fullPath: '/admin/jadwalajar'
      preLoaderRoute: typeof Auth_guruAdminJadwalajarRouteImport
      parentRoute: typeof Auth_guruAdminRoute
    }
    '/_auth_guru/admin/guru': {
      id: '/_auth_guru/admin/guru'
      path: '/guru'
      fullPath: '/admin/guru'
      preLoaderRoute: typeof Auth_guruAdminGuruRouteImport
      parentRoute: typeof Auth_guruAdminRoute
    }
  }
}

interface Auth_guruAdminRouteChildren {
  Auth_guruAdminGuruRoute: typeof Auth_guruAdminGuruRoute
  Auth_guruAdminJadwalajarRoute: typeof Auth_guruAdminJadwalajarRoute
  Auth_guruAdminKelasRoute: typeof Auth_guruAdminKelasRoute
  Auth_guruAdminKetuaKelasRoute: typeof Auth_guruAdminKetuaKelasRoute
  Auth_guruAdminMapelRoute: typeof Auth_guruAdminMapelRoute
  Auth_guruAdminRuanganRoute: typeof Auth_guruAdminRuanganRoute
  Auth_guruAdminIndexRoute: typeof Auth_guruAdminIndexRoute
}

const Auth_guruAdminRouteChildren: Auth_guruAdminRouteChildren = {
  Auth_guruAdminGuruRoute: Auth_guruAdminGuruRoute,
  Auth_guruAdminJadwalajarRoute: Auth_guruAdminJadwalajarRoute,
  Auth_guruAdminKelasRoute: Auth_guruAdminKelasRoute,
  Auth_guruAdminKetuaKelasRoute: Auth_guruAdminKetuaKelasRoute,
  Auth_guruAdminMapelRoute: Auth_guruAdminMapelRoute,
  Auth_guruAdminRuanganRoute: Auth_guruAdminRuanganRoute,
  Auth_guruAdminIndexRoute: Auth_guruAdminIndexRoute,
}

const Auth_guruAdminRouteWithChildren = Auth_guruAdminRoute._addFileChildren(
  Auth_guruAdminRouteChildren,
)

interface Auth_guruGuruRouteChildren {
  Auth_guruGuruJadwalRoute: typeof Auth_guruGuruJadwalRoute
  Auth_guruGuruScanRoute: typeof Auth_guruGuruScanRoute
  Auth_guruGuruIndexRoute: typeof Auth_guruGuruIndexRoute
}

const Auth_guruGuruRouteChildren: Auth_guruGuruRouteChildren = {
  Auth_guruGuruJadwalRoute: Auth_guruGuruJadwalRoute,
  Auth_guruGuruScanRoute: Auth_guruGuruScanRoute,
  Auth_guruGuruIndexRoute: Auth_guruGuruIndexRoute,
}

const Auth_guruGuruRouteWithChildren = Auth_guruGuruRoute._addFileChildren(
  Auth_guruGuruRouteChildren,
)

interface Auth_guruRouteChildren {
  Auth_guruAdminRoute: typeof Auth_guruAdminRouteWithChildren
  Auth_guruGuruRoute: typeof Auth_guruGuruRouteWithChildren
}

const Auth_guruRouteChildren: Auth_guruRouteChildren = {
  Auth_guruAdminRoute: Auth_guruAdminRouteWithChildren,
  Auth_guruGuruRoute: Auth_guruGuruRouteWithChildren,
}

const Auth_guruRouteWithChildren = Auth_guruRoute._addFileChildren(
  Auth_guruRouteChildren,
)

interface Auth_siswaSiswaRouteChildren {
  Auth_siswaSiswaMapelidRoute: typeof Auth_siswaSiswaMapelidRoute
  Auth_siswaSiswaGenerateRoute: typeof Auth_siswaSiswaGenerateRoute
  Auth_siswaSiswaIndexRoute: typeof Auth_siswaSiswaIndexRoute
}

const Auth_siswaSiswaRouteChildren: Auth_siswaSiswaRouteChildren = {
  Auth_siswaSiswaMapelidRoute: Auth_siswaSiswaMapelidRoute,
  Auth_siswaSiswaGenerateRoute: Auth_siswaSiswaGenerateRoute,
  Auth_siswaSiswaIndexRoute: Auth_siswaSiswaIndexRoute,
}

const Auth_siswaSiswaRouteWithChildren = Auth_siswaSiswaRoute._addFileChildren(
  Auth_siswaSiswaRouteChildren,
)

interface Auth_siswaRouteChildren {
  Auth_siswaSiswaRoute: typeof Auth_siswaSiswaRouteWithChildren
}

const Auth_siswaRouteChildren: Auth_siswaRouteChildren = {
  Auth_siswaSiswaRoute: Auth_siswaSiswaRouteWithChildren,
}

const Auth_siswaRouteWithChildren = Auth_siswaRoute._addFileChildren(
  Auth_siswaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Auth_guruRoute: Auth_guruRouteWithChildren,
  Auth_siswaRoute: Auth_siswaRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginGuruRoute: LoginGuruRoute,
  LoginSiswaRoute: LoginSiswaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
