/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AdminGuruImport } from './routes/admin/guru'
import { Route as AdminlayoutImport } from './routes/admin/__layout'
import { Route as AuthGuruImport } from './routes/_auth/guru'
import { Route as AuthGuruIndexImport } from './routes/_auth/guru/index'
import { Route as AuthGuruScanImport } from './routes/_auth/guru/scan'

// Create Virtual Routes

const AdminImport = createFileRoute('/admin')()

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminGuruRoute = AdminGuruImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => AdminRoute,
} as any)

const AdminlayoutRoute = AdminlayoutImport.update({
  id: '/__layout',
  getParentRoute: () => AdminRoute,
} as any)

const AuthGuruRoute = AuthGuruImport.update({
  id: '/guru',
  path: '/guru',
  getParentRoute: () => AuthRoute,
} as any)

const AuthGuruIndexRoute = AuthGuruIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthGuruRoute,
} as any)

const AuthGuruScanRoute = AuthGuruScanImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthGuruRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/guru': {
      id: '/_auth/guru'
      path: '/guru'
      fullPath: '/guru'
      preLoaderRoute: typeof AuthGuruImport
      parentRoute: typeof AuthImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/admin/__layout': {
      id: '/admin/__layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminlayoutImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guru': {
      id: '/admin/guru'
      path: '/guru'
      fullPath: '/admin/guru'
      preLoaderRoute: typeof AdminGuruImport
      parentRoute: typeof AdminImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/_auth/guru/scan': {
      id: '/_auth/guru/scan'
      path: '/scan'
      fullPath: '/guru/scan'
      preLoaderRoute: typeof AuthGuruScanImport
      parentRoute: typeof AuthGuruImport
    }
    '/_auth/guru/': {
      id: '/_auth/guru/'
      path: '/'
      fullPath: '/guru/'
      preLoaderRoute: typeof AuthGuruIndexImport
      parentRoute: typeof AuthGuruImport
    }
  }
}

// Create and export the route tree

interface AuthGuruRouteChildren {
  AuthGuruScanRoute: typeof AuthGuruScanRoute
  AuthGuruIndexRoute: typeof AuthGuruIndexRoute
}

const AuthGuruRouteChildren: AuthGuruRouteChildren = {
  AuthGuruScanRoute: AuthGuruScanRoute,
  AuthGuruIndexRoute: AuthGuruIndexRoute,
}

const AuthGuruRouteWithChildren = AuthGuruRoute._addFileChildren(
  AuthGuruRouteChildren,
)

interface AuthRouteChildren {
  AuthGuruRoute: typeof AuthGuruRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthGuruRoute: AuthGuruRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AdminRouteChildren {
  AdminlayoutRoute: typeof AdminlayoutRoute
  AdminGuruRoute: typeof AdminGuruRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminlayoutRoute: AdminlayoutRoute,
  AdminGuruRoute: AdminGuruRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/guru': typeof AuthGuruRouteWithChildren
  '/admin': typeof AdminlayoutRoute
  '/admin/guru': typeof AdminGuruRoute
  '/admin/': typeof AdminIndexRoute
  '/guru/scan': typeof AuthGuruScanRoute
  '/guru/': typeof AuthGuruIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/guru': typeof AdminGuruRoute
  '/guru/scan': typeof AuthGuruScanRoute
  '/guru': typeof AuthGuruIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/_auth/guru': typeof AuthGuruRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/admin/__layout': typeof AdminlayoutRoute
  '/admin/guru': typeof AdminGuruRoute
  '/admin/': typeof AdminIndexRoute
  '/_auth/guru/scan': typeof AuthGuruScanRoute
  '/_auth/guru/': typeof AuthGuruIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/login'
    | '/guru'
    | '/admin'
    | '/admin/guru'
    | '/admin/'
    | '/guru/scan'
    | '/guru/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/login'
    | '/admin'
    | '/admin/guru'
    | '/guru/scan'
    | '/guru'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/about'
    | '/login'
    | '/_auth/guru'
    | '/admin'
    | '/admin/__layout'
    | '/admin/guru'
    | '/admin/'
    | '/_auth/guru/scan'
    | '/_auth/guru/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  AdminRoute: typeof AdminRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  AdminRoute: AdminRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/about",
        "/login",
        "/admin"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/guru"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/guru": {
      "filePath": "_auth/guru.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/guru/scan",
        "/_auth/guru/"
      ]
    },
    "/admin": {
      "filePath": "admin",
      "children": [
        "/admin/__layout",
        "/admin/guru",
        "/admin/"
      ]
    },
    "/admin/__layout": {
      "filePath": "admin/__layout.tsx",
      "parent": "/admin"
    },
    "/admin/guru": {
      "filePath": "admin/guru.tsx",
      "parent": "/admin"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/_auth/guru/scan": {
      "filePath": "_auth/guru/scan.tsx",
      "parent": "/_auth/guru"
    },
    "/_auth/guru/": {
      "filePath": "_auth/guru/index.tsx",
      "parent": "/_auth/guru"
    }
  }
}
ROUTE_MANIFEST_END */
